source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!


target 'YYTextView@Demon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#  use_frameworks!

pod 'Masonry'


pod 'YYWebImage'
pod 'YYImage/WebP'
pod 'YYImage'
pod 'YYText'
pod 'YYCache'




end


